### ISSUE TITLE
Error on compiling

### ISSUE THREAD

**Issue by laulin510** [kannX/phs-latex-templates#3]
Beim compilen der Datei entsteht folgender Fehler in der Einstellungen.tex Datei.

C:\texlive\2023\bin\windows\runscript.tlu:921: command failed with exit code 12:
perl.exe c:\texlive\2023\texmf-dist\scripts\latexmk\latexmk.pl -synctex=1 -interaction=nonstopmode -file-line-error -pdf -outdir=d:/Uni/Bachelorarbeit/Expos� d:/Uni/Bachelorarbeit/Expos�/Einstellungen

**Comment by kannX** [comment]
Ich würde hier erstmal ein Problem mit dem Ordnernamen vermuten, und nicht der Einstellungen.tex.
Gleicher Fehler ohne Sonderzeichen in der Verzeichnisstruktur?

**Comment by jaspreetso** [comment]
Der Error ist auch unter dem Pfad:
perl.exe c:\texlive\2023\texmf-dist\scripts\latexmk\latexmk.pl -synctex=1 -interaction=nonstopmode -file-line-error -pdf -outdir=c:/Users/jaspr/iCloudDrive/Documents/Provadis/Bachelorarbeit/Bachelorarbeit/out c:/Users/jaspr/iCloudDrive/Documents/Provadis/Bachelorarbeit/Bachelorarbeit/Einstellungen

weiterhin vorhanden

**Comment by jaspreetso** [comment]
Ich konnte den Fehler darauf zurückführen, dass es ein Editor Problem ist.
Es gibt eine Hierarchie für den Latex Kompiler, der 

1. Nach der manuell "Main"-Datei sucht
2. Nach dem Befehl `\documentclass` sucht

Da wir in unserem Beispiel die Main-Datei nicht gesetzt haben (VS Code wird als Editor benutzt) versucht Latex die Einstellungen.tex als Main-Datei zu kompilieren.

Daher der Vorschlag

- Entweder wird der Befehl in die Main-Datei verlagert (das für alle beteiligt am sinnvollsten wäre meiner Meinung nach)
- Ein Hinweis in der Readme, sodass diese richtig konfiguriert werden kann.

Ich wäre für die erste Option, da das Template dann out-of-the-box funktioniert

**Comment by kannX** [comment]
Erste Option in commit 138436e umgesetzt.
